version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/Assembler" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/Z80Assembler" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
